### ISSUE TITLE
No access to  the tables from  ACME Virtuoso Catalog in Superset Datasource configuration

### ISSUE THREAD

**Issue by E-Babkin** [OpenLinkSoftware/Virtuoso-SQLAlchemy#5]
if the odbc.ini  uses ACME Virtuoso catalog (Database=ACME),
Table dropdown list in Superset still displays tables from DB Virtuoso catalog.

A standalone test python program correctly connects to ACME and gets results. 

It may be connected with  https://github.com/OpenLinkSoftware/Virtuoso-SQLAlchemy/issues/4

**Comment by E-Babkin** [comment]
After restart of the Superset container the list of the tables was updated.

**Comment by smalinin** [comment]
It may be because you updated odbc.ini when superset is already worked, so it may reuse prev cached connection.
